---
title: NUS Psychology Concurrent Degree Program. Should I Apply?
author: Aaron Lim Jin Ming
date: '2020-06-20'
slug: should-i-apply-for-the-nus-psychology-concurrent-degree-program
categories:
  - review
  - NUS
tags:
  - NUS
  - CDP
  - Concurrent
  - Degree
  - Program
  - Psychology
description: 'Should I apply for the Psychology Concurrent Degree Program (CDP) offered in the National University of Singapore (NUS)?'
keywords: 
  - NUS
  - Psychology
  - CDP
  - Concurrent Degree Program
  - Review
  - Apply
stylesheet: post.css
---

Every year, the department of Psychology in NUS sends out little postcards to the second-year undergraduates inviting them to apply for the **Concurrent Degree Program (CDP)**. More often than not, these postcards are met with confusion over what this program actually is. The [department website](https://www.fas.nus.edu.sg/psy/prospective/index.html#concurrent) gives a good introduction to what the program offers and this post aims to complement the website. Providing a more student-centric explanation/reflection about the program and the frequently asked questions (from juniors) that are not found on the website.
 
Firstly, an introduction to the CDP in NUS Psychology. In essence, it condenses the **Bachelor of Social Sciences (Hons)** and **Master of Social Science (Psychology by Research)** into one package. Doing the two degrees separately would require *6* years, *4* for the Bachelor program and *2* for the Masters program. In contrast, the CDP only takes *5* years. Some questions that are frequently asked:

> How does it condense the two programs?

Mainly by increasing the workload for the last *2* years. In the last two years, we had to take on the workload of a Masters student + the coursework requirement of the Bachelor (Hons) program. Luckily we only needed to do one thesis for both programs.

> Sounds great but are there any drawbacks to this program?

Other than the increased workload, here are some of the drawbacks that I am aware of.

* Due to the increased workload, you have less time and resources for your thesis compared to a full-time Masters student.
* Tuition fees for the last two years are charged according to the Masters program, which is slightly more expensive than the Bachelor program.
* Additional year of study is an additional year of fees.
* Opportunity cost, one more year of studying is one less year of working.
* Ample preparation is needed to apply for the program.

> Should I apply for the CDP?

* Consider a few things: Do you have a career plan?
    * If your plan requires a Masters --> Does it require a research-based degree?
        * This is important because the Masters degree from the CDP is a **research** degree. And from my own experience talking to seniors and HR, this is not a perfect replacement for specialized degrees such as Clinical or I/O Psychology degrees.
    * If your plan does not require a Masters, but it requires a Phd instead.
        * If you are confident that you can enroll directly into a Phd program after your Bachelors, I would say just skip the Masters and the CDP.
        * On the other hand, having a Masters (in Research) would benefit your Phd application. So it can increase your odds of getting into the more prestigious programs. 
            * Your thesis would also have a higher likelihood of being published as you have more time to work on it compared to an undergraduate. This would greatly benefit your Phd application as publications remain the best ticket to Phd programs.
    * If your plan does not require a Masters or a Phd.
        * Then nope.
* But should I get a Masters even if my plan does not require it or I have no plan? I may need it in the future.
    * This is a tough one. I would say no, as it is possible that your company may sponsor your Masters degree if your job really requires it. And it is also possible they would require a more specialized degree.
        
> Sweet, I want to apply for the CDP! What do I need?

This would be the toughest part (my opinion) of CDP. As per the website, it is recommended to apply by the end of your Year 3, Semester 1 if you intend to begin the Masters program in Year 4 Semester 1. But there are quite a few requirements...

|Requirements|
|--------|    
|1. Majoring in Psychology|
|2. Passed the following essential modules (PL1101E, PL2131, PL2132, PL3232, PL3233, PL3234, PL3235, PL3236, and PL3231 OR PL328x)|
|3. Cumulative Average Point (CAP) ≥ 4.0 & Psychology Subject Average Point (SJAP) ≥ 4.3 (at the time of application)|
|4. Average grade of A- for PL2131, PL2132, and either PL3231 or PL328x (no lower than B+ for any of these modules)|
|5. TWO (or more) recommendation/referee letters|
|6. Personal Statement and a rank-ordered list of potential thesis supervisors|

The biggest question relating to the requirements is:

> I intend to take PL328x in Year 3 Semester 2, but it is one of the requirements for application! Does that mean I cannot apply?

Actually, you **can**. All you have to do is to make it known to the coordinator during your application and they will defer the requirement.
    
Other questions include:

> How do I get recommendation letters?

Recommendation letter requirements vary from Professors to Professors. But the best advice would be to start early! Remember that it is a research program so the writers should have some idea of your research capabilities. Some common avenues to get recommendation letters are working as research assistants, performing outstandingly in a research module or doing an independent research project (PL3231 or PL3551 UROP) with the professor. These are commitments that span at least a semester.
*Note: I am using "Professor" loosely here to refer to any faculty member.*

> Do I have to get recommendation letters from Professors of the same field of study?

Nope.

> Do I have to get recommendation letters from Professors in NUS?

Technically no, just that NUS faculty members would be the most easily accessible source of recommendation letters. It is possible for faculty members of other universities to write these letters for you. But it would be best to check with the administration staffs as these requirements may have changed since my time. Also, full-time teaching assistants can also write these letters, but it would be best to check with the staffs about this.

> Is the CDP tough?

This varies greatly from person to person and depends on your domain of research as well. Personally, I found the program to be manageable and quite a joy to be in. But my experience is rather unique, as my research topic did not require me to conduct any experiments as I ran simulations on large amounts of data. So I was spared the pain of collecting data. One thing for certain is that the CDP is **research intensive**. On top of the thesis, there are additional compulsory modules that are focused on research and statistics. These can be a great source of frustration and anxiety as I witnessed from my peers. But I will leave my reflection and review for another post as this is getting lengthy.

I hope that this post was useful for those thinking about applying for the CDP!
